---
title: "benchmarking-dct"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{benchmarking-dct}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tsrecipes)
library(tidyverse)
```

```{r}
library(dtt)
```

```{r}
tsdb <- tsrecipes::prices$ts
ts <- tsdb[[1]]
```

```{r}
x <- ts
```

```{r}
dct_dtt <- dtt::dct
bench_ts <- bench::mark(
  fdct(ts),
  dct_dtt(ts)
)
```

```{r}
bench_ts %>%
  select(expression, min, median, mem_alloc)
```



```{r}
dct_so_apply <- function(l) {
  l %>%
    simplify2array() %>%
    t() %>%
    apply(1, fdct) %>%
    t()
}

dct_so_mv <- function(l) {
   l %>%
    simplify2array() %>%
    mvfdct() %>%
    t()
}
```


```{r}
dct_dtt_apply <- function(l) {
  l %>%
    simplify2array() %>%
    t() %>%
    apply(1, dtt::dct) %>%
    t()
}

dct_dtt_mv <- function(l) {
  l %>%
    simplify2array() %>%
    t() %>% 
    dct()
}

bench_tsdb <- bench::mark(
  dct_dtt_apply(tsdb),
  dct_dtt_mv(tsdb),
  dct_so_apply(tsdb),
  dct_so_mv(tsdb)
)
```

```{r}
bench_tsdb %>%
  select(expression, min, median, mem_alloc)
```

## Inverse

```{r}
its <- dct_dtt(ts)
```


```{r}
bench_its <- bench::mark(
  dct_dtt(its, inverted = TRUE)
)
```

```{r}
bench_its %>%
  select(expression, min, median, mem_alloc)
```





```{r}
df <- tibble(
  n = 1:60,
  ts = ts,
  reconstruct = dct_dtt(ifelse(its > 8, its, 0), inverted = TRUE)
) 
```

```{r}
its[ifelse(its > 8, its, 0) != 0] %>% length()
```



```{r}
df %>%
  ggplot(aes(n)) +
  geom_line(aes(y = ts), color = "red") +
  geom_line(aes(y = reconstruct), color = "blue")
```

