---
title: "dynamic-time-warping"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dynamic-time-warping}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(tsrecipes)
library(tidyverse)
library(dtwclust)
```

```{r}
ethanol
```


```{r}
if (!file.exists("ethclust.RDS")) {
  ethclust <- tsclust(ethanol$ts, k = 3)
  saveRDS(ethclust, "ethclust.RDS")
}

clusters <- readRDS("ethclust.RDS")
```

```{r}
clusters@cluster
```

```{r}
all(
  predict(clusters, ethanol$ts) == clusters@cluster
)
```

```{r}

output_cl <- list(dtwclust_ts = clusters@cluster)

output_cl <- tibble()
output_cl[["dtwclust_ts"]] <- clusters@cluster
```

```{r}
output_cl %>%
  imap(~tibble::tibble(!!.y := .x)) %>%
  bind_cols(ethanol, .)
```

```{r}
tibble(!!!output_cl)
```





```{r}
fn <- function(a, b) {
  print(paste0(a, " ", b))
}

do.call(fn, c(list(a = 1), list(b = 2)))
```



